name: livelyco
services:
  livelyco:
    container_name: livelyco
    build:
      context: .
      dockerfile: ./Staging.Dockerfile
#    image: ethanbrowning/livelyfencing-staging
    restart: unless-stopped
    pull_policy: always
    ports:
      - $FRONTEND_PORT:$FRONTEND_PORT
      - 8148:8148
    networks:
      nginxproxymanager:
    environment:
      HOST: $HOST
      FRONTEND_PORT: $FRONTEND_PORT
      USER_EMAIL: $USER_EMAIL
      USER_PASS: $USER_PASS
      SEND_TO: $SEND_TO
    volumes:
      - ./contact-entries:/livelyco/backend/data
    healthcheck:
      test: bun /livelyco/backend/src/health.ts || exit 1
      interval: 60s
      retries: 5
      start_period: 20s
      timeout: 10s

networks:
  nginxproxymanager:
    external: true
