name: livelyco

# services go here
services:

  livelyco:
    build: .
    ports:
      - 8157:8157
    restart: unless-stopped
    environment:
      PORT: 8157
    networks:
      livelyco:

  lively_backend:
    build: ./server
    container_name: lively_backend
    ports:
      - 8158:8158
    networks:
      livelyco:
    volumes:
      - ./contact-entries:/backend/data

networks:
  livelyco:
    name: livelyco



  # database container
#  database:
#    image: postgres
#    ports:
#      - 5432:5432
#    environment:
#      POSTGRES_PASSWORD: mysecretpassword
