name: livelyco
services:
  livelyco:
    container_name: livelyco
    image: ethanbrowning/livelyfencing:latest
    restart: unless-stopped
    pull_policy: always
    ports:
      - $FRONTEND_PORT:$FRONTEND_PORT
    networks:
      nginxproxymanager:
      livelyco:
    environment:
      HOST: $HOST
      FRONTEND_PORT: $FRONTEND_PORT

  lively_backend:
    image: ethanbrowning/livelyfencing-backend:latest
    container_name: lively_backend
    restart: unless-stopped
    pull_policy: always
    ports:
      - 8158:8158
    networks:
      livelyco:
    environment:
      HOST: $HOST
      FRONTEND_PORT: $FRONTEND_PORT
      USER_EMAIL: $USER_EMAIL
      USER_PASS: $USER_PASS
      SEND_TO: $SEND_TO
    volumes:
      - ./contact-entries:/backend/data
    healthcheck:
      test: bun /backend/src/health || exit 1
      interval: 60s
      retries: 5
      start_period: 20s
      timeout: 10s

networks:
  nginxproxymanager:
    external: true
