name: lively-staging
services:
  livelyco:
    container_name: lively-staging
    build:
      context: .
      dockerfile: ./Staging.Dockerfile
    #image: ethanbrowning/livelyfencing:staging
    restart: unless-stopped
    pull_policy: always
    ports:
      - $FRONTEND_PORT:$FRONTEND_PORT
      - $BACKEND_PORT:$BACKEND_PORT
    # networks:
    #  nginxproxymanager:
    environment:
      HOST: $HOST
      FRONTEND_PORT: $FRONTEND_PORT
      BACKEND_PORT: $BACKEND_PORT
      USER_EMAIL: $USER_EMAIL
      USER_PASS: $USER_PASS
      SEND_TO: $SEND_TO
      NODE_ENV: $NODE_ENV
      KEY_FILE: $KEY_FILE
      DRIVE_ID: $DRIVE_ID
#    volumes:
#      - ./contact-entries:/home/lively/backend/data
    healthcheck:
      test: bun /home/lively/backend/src/health.ts || exit 1
      interval: 60s
      retries: 5
      start_period: 20s
      timeout: 10s

#networks:
#  nginxproxymanager:
#    external: true
