name: basics

# services go here
services:

  # backend container
  basics:
    image: garretpremo/basics
    ports:
      - 8156:8156

  # database container
  database:
    image: postgres
    ports:
      - 5432:5432
    environment:
      POSTGRES_PASSWORD: mysecretpassword
