name: livelyco
services:
  livelyco:
    container_name: livelyco
    image: ethanbrowning/LivelyFencing
    ports:
      - 8156:8156
    networks:
      nginxproxymanager:

networks:
  nginxproxymanager:
    external: true
