name: livelyco

# services go here
services:

  # backend container
  livelyco:
    build: .
    ports:
      - 8156:8156

  # database container
#  database:
#    image: postgres
#    ports:
#      - 5432:5432
#    environment:
#      POSTGRES_PASSWORD: mysecretpassword
