name: livelyco
services:
  livelyco:
    container_name: livelyco
    image: ethanbrowning/livelyfencing:latest
    restart: unless-stopped
    pull_policy: always
    ports:
      - 8157:8157
    networks:
      nginxproxymanager:
      livelyco:
    environment:
      PORT: 8157

  lively_backend:
    build: ./server
    container_name: lively_backend
    ports:
      - 8158:8158
    networks:
      livelyco:
    volumes:
      - ./contact-entries:/backend/data

networks:
  nginxproxymanager:
    external: true
