name: livelyco
services:
  livelyco:
    container_name: livelyco
    image: ethanbrowning/livelyfencing:production
    restart: unless-stopped
    pull_policy: always
    ports:
      - $FRONTEND_PORT:$FRONTEND_PORT
      - $BACKEND_PORT:$BACKEND_PORT
    networks:
      proxy:
    environment:
      HOST: $HOST
      FRONTEND_PORT: $FRONTEND_PORT
      BACKEND_PORT: $BACKEND_PORT
      USER_EMAIL: $USER_EMAIL
      USER_PASS: $USER_PASS
      SEND_TO: $SEND_TO
#    volumes:
#      - ./contact-entries:/home/lively/backend/data
    healthcheck:
      test: bun /home/lively/backend/src/health.ts || exit 1
      interval: 60s
      retries: 5
      start_period: 20s
      timeout: 10s

networks:
  proxy:
    external: true
